version: '3'

services:
  backend:
    image: 094908652183.dkr.ecr.ap-northeast-1.amazonaws.com/goonstone_backend
    build:
      context: ./containers/backend
      dockerfile: ./build/Dockerfile
    env_file:
      - containers/backend/prod.env
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: goonstone-cluster-01
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: backend

  frontend:
    image: 094908652183.dkr.ecr.ap-northeast-1.amazonaws.com/goonstone_frontend
    build:
      context: ./containers/frontend
      dockerfile: containers/frontend/build/Dockerfile.dev
    env_file:
      - containers/frontend/prod.env
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: goonstone-cluster-01
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: frontend
