version: '3'

services:
  backend:
    image: goonstone_backend:latest
    build:
      context: ./containers/backend
      dockerfile: ./build/Dockerfile
    tty: true
    restart: always
    env_file:
      - ./containers/backend/.env
    ports:
      - 80:80
    volumes:
      - ./containers/backend:/go/src/Goonstone

  db:
    build:
      context: ./containers/db
      dockerfile: ./build/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    env_file:
      - ./containers/db/.env
    ports:
      - 3306:3306
    volumes:
      - ./containers/db/data:/var/lib/mysql
      - ./containers/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./containers/db/sql:/docker-entrypoint-initdb.d

  frontend:
    image: goonstone_frontend:latest
    build:
      context: ./containers/frontend
      dockerfile: ./build/Dockerfile
    tty: true
    restart: always
    env_file:
      - ./containers/frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./containers/frontend:/app
